spring:
  application:
    name: em-bank-rest
  datasource:
    url: jdbc:postgresql://localhost:5432/em_bank_rest
    username: postgres
    password: 1
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    sql: debug
    web: debug

app:
    msg:
      user_id_not_null: User ID must be null
      user_id_positive: User ID must be positive
      id_positive: ID must be positive
