spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/em_bank_rest
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
management:
  endpoints:
    web:
      exposure:
        include:
          - health
