spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/em_bank_rest
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1}
management:
  endpoints:
    web:
      exposure:
        include:
          - health
app:
  jwt-secret: mominfactilovefrogsfrogsfrogsfrogsfrogsfrogs
  access-token-expiration: "#{1000 * 60 * 60}"
  refresh-token-expiration: "#{1000 * 60 * 60 * 24 * 7}"