openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0

servers:
  - url: http://localhost:8080
    description: Generated server url

paths:
  /api/v1/admin/users:
    $ref: './paths/admin-users.yaml'
  /api/v1/admin/users/{userId}:
    $ref: './paths/admin-user-by-id.yaml'
  /api/v1/admin/cards:
    $ref: './paths/admin-cards.yaml'
  /api/v1/admin/cards/{cardId}:
    $ref: './paths/admin-card-by-id.yaml'

components:
  schemas:
    GetCreatePatchUserResponse:
      $ref: './components/schemas/user.yaml#/GetCreatePatchUserResponse'
    PatchUserRequest:
      $ref: './components/schemas/user.yaml#/PatchUserRequest'
    PagedModelGetCreatePatchUserResponse:
      $ref: './components/schemas/user.yaml#/PagedModelGetCreatePatchUserResponse'
    PageMetadata:
      $ref: './components/schemas/common.yaml#/PageMetadata'
    TransferBetweenCardsRequest:
      $ref: './components/schemas/card.yaml#/TransferBetweenCardsRequest'
    CreateCardRequest:
      $ref: './components/schemas/card.yaml#/CreateCardRequest'
    GetCreatePatchCardResponse:
      $ref: './components/schemas/card.yaml#/GetCreatePatchCardResponse'
    UpdateStatusCardRequest:
      $ref: './components/schemas/card.yaml#/UpdateStatusCardRequest'
    PagedModelGetCreatePatchCardResponse:
      $ref: './components/schemas/card.yaml#/PagedModelGetCreatePatchCardResponse'
